# Generated by Django 5.0.7 on 2024-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
