# Generated by Django 5.0.6 on 2024-07-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_content'),
        ('todo', '0003_alter_task_subject'),
    ]

    operations = [
    ]
